name: key2med
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - pip:
     - -r requirements.txt
     - -e .  # install git checkout of key2med in editable mode
